// Preliminary Physics — Section I multiple-choice questions
// Sourced from the 2021 NSW Independent Trial Exams, Physics Year 11 Examination,
// cross-checked against that paper's own official marking guidelines. Question
// images are direct crops of the original exam PDF pages.
const QUESTIONS = [
  {
    "id": "P23-Q1",
    "year": 2023,
    "n": 1,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "P23_mc01.png",
    "w": 1644,
    "h": 1239,
    "ans": ["D"],
    "expl": "A car moving in a positive direction with increasing acceleration has a velocity that increases over time at an ever-steeper rate — a curve that starts shallow and gets steeper, which is graph D."
  },
  {
    "id": "P23-Q2",
    "year": 2023,
    "n": 2,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "P23_mc02.png",
    "w": 1644,
    "h": 961,
    "ans": ["B"],
    "expl": "Since the car travels 20 km along the road in exactly one hour, its average speed for the whole journey is fixed at 20 km/h — it cannot be more or less than that. But if the car's speed varies during the trip (speeding up then slowing down), its instantaneous speed could exceed 20 km/h at some points."
  },
  {
    "id": "P23-Q3",
    "year": 2023,
    "n": 3,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "P23_mc03.png",
    "w": 1644,
    "h": 1314,
    "ans": ["B"],
    "expl": "Light refracts (bends) at both surfaces of a prism, bending toward the normal as it enters the denser glass and then dispersing further as it exits. Diagram B shows the incoming white light bending at the first (entry) surface before spreading into the spectrum at the exit surface, which is physically correct; diagram A incorrectly shows the beam travelling straight through the glass with no bend at all until it reaches the exit face."
  },
  {
    "id": "P23-Q4",
    "year": 2023,
    "n": 4,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "P23_mc04.png",
    "w": 1644,
    "h": 973,
    "ans": ["C"],
    "expl": "Refraction (a change in direction) is only guaranteed when a wave's speed changes AND it meets the new medium at a non-zero angle to the normal (e.g. 45 degrees) — at normal incidence, a speed and wavelength change occurs but the wave does not bend."
  },
  {
    "id": "P23-Q5",
    "year": 2023,
    "n": 5,
    "topic": "Kinematics",
    "subs": ["Motion on a Plane"],
    "img": "P23_mc05.png",
    "w": 1644,
    "h": 1213,
    "ans": ["B"],
    "expl": "Relative velocity of black car with respect to white car = velocity of black − velocity of white = (20 m/s east) − (20 m/s north) = 20 m/s east + 20 m/s south, which points south-east."
  },
  {
    "id": "P23-Q6",
    "year": 2023,
    "n": 6,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "P23_mc06.png",
    "w": 1644,
    "h": 1112,
    "ans": ["A"],
    "expl": "Once the desk is tilted just past the angle needed to overcome static friction and held at that fixed angle, the net force down the slope (gravity component minus kinetic friction) stays constant, so the book accelerates uniformly (constantly increasing speed) as it slides — it is accelerating."
  },
  {
    "id": "P23-Q7",
    "year": 2023,
    "n": 7,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "P23_mc07.png",
    "w": 1644,
    "h": 1668,
    "ans": ["C"],
    "expl": "Maximum speed on a horizontal road occurs where the driving force the engine can supply (F = P/v) equals the friction force read from the graph. Testing the options: at v = 40 m/s, the required force 80,000 W / 40 m/s = 2000 N matches the friction force shown on the graph at that speed, and 40 m/s = 144 km/h."
  },
  {
    "id": "P23-Q8",
    "year": 2023,
    "n": 8,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "P23_mc08.png",
    "w": 1644,
    "h": 1163,
    "ans": ["D"],
    "expl": "Conserving momentum along the original direction: 6.0 x 12.0 = 2 x (3.0 x v x cos40 degrees), so v = 72 / (6.0 x cos40 degrees) = 15.7 m/s."
  },
  {
    "id": "P23-Q9",
    "year": 2023,
    "n": 9,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "P23_mc09.svg",
    "w": 900,
    "h": 448,
    "ans": ["C"],
    "expl": "An internal explosion converts stored (e.g. chemical or elastic) energy into kinetic energy, so kinetic energy increases rather than being conserved — but momentum, having no external horizontal force acting on the system, is always conserved."
  },
  {
    "id": "P23-Q10",
    "year": 2023,
    "n": 10,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Properties"],
    "img": "P23_mc10.png",
    "w": 1644,
    "h": 658,
    "ans": ["B"],
    "expl": "Waves transfer energy without transferring matter. The clearest evidence that a wave itself carries usable energy is that our ears convert the energy of an incoming sound wave into electrical impulses sent to the brain — the wave has done work."
  },
  {
    "id": "P23-Q11",
    "year": 2023,
    "n": 11,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Properties"],
    "img": "P23_mc11.png",
    "w": 1644,
    "h": 632,
    "ans": ["B"],
    "expl": "A boat floating on the surface of a water wave simply bobs up and down (transverse oscillation) at the wave's frequency, without travelling with the wave. At f = 0.10 Hz, it completes one full up-and-down cycle every 10 s, i.e. 6 cycles every minute — up and down 6 times each minute."
  },
  {
    "id": "P23-Q12",
    "year": 2023,
    "n": 12,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "P23_mc12.png",
    "w": 1644,
    "h": 1567,
    "ans": ["C"],
    "expl": "The elephant's 500 N pull at N60 degrees E has a northward component of 500cos60 degrees = 250 N, which the girl pulling due south must balance exactly for equilibrium, so she must pull with 250 N."
  },
  {
    "id": "P23-Q13",
    "year": 2023,
    "n": 13,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "P23_mc13.png",
    "w": 1644,
    "h": 2047,
    "ans": ["A"],
    "expl": "For an object placed between the lens and its focal point F, a converging lens forms an enlarged, upright, virtual image on the same side as the object — matching both the ray construction (dashed rays diverging, extended backward to locate the image) and the description given in option A."
  },
  {
    "id": "P23-Q14",
    "year": 2023,
    "n": 14,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "P23_mc14.svg",
    "w": 900,
    "h": 411,
    "ans": ["C"],
    "expl": "Doubling the observed frequency from 500 Hz to 1000 Hz requires the source to close the gap at half the speed of sound (170 m/s) while approaching, by the Doppler effect formula f' = f x v/(v - vs): 1000 = 500 x 340/(340-170)."
  },
  {
    "id": "P23-Q15",
    "year": 2023,
    "n": 15,
    "topic": "Waves and Thermodynamics",
    "subs": ["Thermodynamics"],
    "img": "P23_mc15.png",
    "w": 1644,
    "h": 948,
    "ans": ["D"],
    "expl": "Heat conducted Q = (kAΔT/L) x t = (15.0 x 2.5e-5 x 30.0 / 0.250) x 300 = 13.5 J."
  },
  {
    "id": "P23-Q16",
    "year": 2023,
    "n": 16,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "P23_mc16.png",
    "w": 1644,
    "h": 1466,
    "ans": ["A"],
    "expl": "Car A's displacement-time graph is a curve (constant acceleration from rest) reaching 100 m at t = 10 s, while car B, starting 5.0 s later at constant speed, is a straight line from (5,0) also reaching 100 m at t = 10 s — this matches graph A, where both curves meet at (10,100) with A curving from t = 0 and B as a straight line starting at t = 5."
  },
  {
    "id": "P23-Q17",
    "year": 2023,
    "n": 17,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "P23_mc17.png",
    "w": 1644,
    "h": 1036,
    "ans": ["A"],
    "expl": "Equipotential lines are always perpendicular to the electric field and, for a point charge, the field points radially outward — so the equipotential surfaces are concentric circles (or spheres) centred on the charge, as in diagram A."
  },
  {
    "id": "P23-Q18",
    "year": 2023,
    "n": 18,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "P23_mc18.png",
    "w": 1644,
    "h": 935,
    "ans": ["A"],
    "expl": "Current I = P/V = 720 W / 240 V = 3.0 A. Since current is the rate of charge flow (1 A = 1 coulomb per second), 3.0 coulombs of charge flow through the hairdryer every second."
  },
  {
    "id": "P23-Q19",
    "year": 2023,
    "n": 19,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "P23_mc19.png",
    "w": 1644,
    "h": 961,
    "ans": ["C"],
    "expl": "Total resistance = series resistor + parallel pair: (A) 20+10=30 ohm, (B) 30+15=45 ohm, (C) 20+30=50 ohm, (D) 30+15=45 ohm. Option C gives the greatest total resistance, 50 ohm."
  },
  {
    "id": "P23-Q20",
    "year": 2023,
    "n": 20,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "P23_mc20.png",
    "w": 1644,
    "h": 1277,
    "ans": ["C"],
    "expl": "The magnetic field strength of a solenoid is proportional to (number of turns x current)/length. The original value is (500 x 2.5)/280 = 4.46. Only option C, with length halved to 140 mm and turns/current unchanged, doubles this ratio to 8.93 — the other options leave it unchanged or halve it."
  },
  {
    "id": "PYM24-Q1",
    "year": 2024,
    "n": 1,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "PYM24_mc01.png",
    "w": 1205,
    "h": 1686,
    "ans": ["A"],
    "expl": "The v-t graph shows uniform acceleration from rest, so velocity increases linearly, displacement increases with a curving (quadratic) shape, and acceleration is constant (a flat horizontal line) — matching option A."
  },
  {
    "id": "PYM24-Q2",
    "year": 2024,
    "n": 2,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "PYM24_mc02.png",
    "w": 1205,
    "h": 1075,
    "ans": ["C"],
    "expl": "The graph shows a nonzero positive velocity at t=0 (so statement 3, that initial velocity is zero, is incorrect), with the value decreasing steadily under gravity, then two sudden jumps back to a positive value (the two floor bounces, so statement 2 is correct). Since velocity is positive while the object is moving toward the floor, downward — not upward — was taken as positive, making both statement 1 (initially goes upwards) and statement 4 (upward taken as positive) incorrect. So statements 1, 3 and 4 are the incorrect ones."
  },
  {
    "id": "PYM24-Q3",
    "year": 2024,
    "n": 3,
    "topic": "Kinematics",
    "subs": ["Motion on a Plane"],
    "img": "PYM24_mc03.png",
    "w": 1205,
    "h": 594,
    "ans": ["A"],
    "expl": "With no air resistance, both stones experience the same downward acceleration g regardless of their initial direction of throw. By symmetry, stone X (thrown up) returns to the throwing height with the same speed v it started with (now directed downward), so from that point both stones fall the same remaining distance under the same acceleration — they hit the ground with equal speed."
  },
  {
    "id": "PYM24-Q4",
    "year": 2024,
    "n": 4,
    "topic": "Kinematics",
    "subs": ["Motion on a Plane"],
    "img": "PYM24_mc04.png",
    "w": 1205,
    "h": 446,
    "ans": ["C"],
    "expl": "The horizontal component of a velocity at an angle above the horizontal is found using cosine of that angle: 50 cos(65) m/s."
  },
  {
    "id": "PYM24-Q5",
    "year": 2024,
    "n": 5,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "PYM24_mc05.png",
    "w": 1205,
    "h": 593,
    "ans": ["B"],
    "expl": "Since the box does not accelerate vertically, the vertical forces balance: the normal force must support the weight against the downward vertical component of F (F cos theta, since theta is measured from the vertical here), so weight = F_N - F cos theta."
  },
  {
    "id": "PYM24-Q6",
    "year": 2024,
    "n": 6,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "PYM24_mc06.png",
    "w": 1205,
    "h": 353,
    "ans": ["B"],
    "expl": "Time = energy / power = 79,000,000 J / 2000 W = 39,500 s, which is about 11 hours."
  },
  {
    "id": "PYM24-Q7",
    "year": 2024,
    "n": 7,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "PYM24_mc07.png",
    "w": 1205,
    "h": 464,
    "ans": ["A"],
    "expl": "By Newton's First Law, an object moving at constant velocity has zero net (resultant) force acting on it."
  },
  {
    "id": "PYM24-Q8",
    "year": 2024,
    "n": 8,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "PYM24_mc08.png",
    "w": 1205,
    "h": 446,
    "ans": ["B"],
    "expl": "Velocity = momentum / mass = 30 / 5.0 = 6.0 m/s. Kinetic energy = 1/2 m v^2 = 0.5 x 5.0 x 6.0^2 = 90 J."
  },
  {
    "id": "PYM24-Q9",
    "year": 2024,
    "n": 9,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "PYM24_mc09.png",
    "w": 1205,
    "h": 408,
    "ans": ["C"],
    "expl": "Noise-cancelling headphones emit a sound wave that overlaps with the background noise wave so that they combine (superpose) destructively, cancelling out — this is the principle of superposition."
  },
  {
    "id": "PYM24-Q10",
    "year": 2024,
    "n": 10,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Properties"],
    "img": "PYM24_mc10.png",
    "w": 1205,
    "h": 371,
    "ans": ["A"],
    "expl": "Intensity follows an inverse square law with distance: I is proportional to 1/d^2. At 4d, the intensity is I / 4^2 = I/16."
  },
  {
    "id": "PYM24-Q11",
    "year": 2024,
    "n": 11,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "PYM24_mc11.png",
    "w": 1205,
    "h": 631,
    "ans": ["B"],
    "expl": "An object placed at 2F in front of a converging lens forms a real, inverted image at 2F on the other side, the same size as the object — matching option B."
  },
  {
    "id": "PYM24-Q12",
    "year": 2024,
    "n": 12,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "PYM24_mc12.png",
    "w": 1205,
    "h": 612,
    "ans": ["D"],
    "expl": "By symmetry, at a point equidistant from two equal positive charges, the horizontal components of the two repulsive fields cancel and the vertical components add, producing a net field pointing straight away from both charges — direction D."
  },
  {
    "id": "PYM24-Q13",
    "year": 2024,
    "n": 13,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "PYM24_mc13.png",
    "w": 1205,
    "h": 464,
    "ans": ["A"],
    "expl": "Electric field strength is defined as force per unit charge, E = F/q, so its units are newtons per coulomb."
  },
  {
    "id": "PYM24-Q14",
    "year": 2024,
    "n": 14,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "PYM24_mc14.png",
    "w": 1205,
    "h": 798,
    "ans": ["D"],
    "expl": "R1 and R2 are in series, so the same (smaller) current flows through the whole loop. R3 and R4 are identical resistors in parallel, so each branch independently carries the full-voltage current, which is twice what a same-resistance series pair would carry — making the series current (R1, R2) half the parallel branch current (R3, R4)."
  },
  {
    "id": "PYM24-Q15",
    "year": 2024,
    "n": 15,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "PYM24_mc15.png",
    "w": 1205,
    "h": 761,
    "ans": ["D"],
    "expl": "Since lamps 1 to 9 are glowing brightly (current is flowing through the series circuit), the circuit is not broken. A lamp with a much lower resistance than the others in a series circuit drops very little voltage across it and dissipates little power, so it does not glow brightly even though current still flows through it."
  },
  {
    "id": "JR20-Q1",
    "year": 2020,
    "n": 1,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "JR20_mc01.png",
    "w": 1205,
    "h": 1038,
    "ans": ["D"],
    "expl": "Total distance = area under the velocity-time graph. Summing the trapezoidal areas from t=0 to 5s (about 24.5 m, using the plotted points) plus the constant-velocity rectangle from t=5 to 15s (9 m/s x 10 s = 90 m) gives approximately 113 m."
  },
  {
    "id": "JR20-Q2",
    "year": 2020,
    "n": 2,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "JR20_mc02.png",
    "w": 1205,
    "h": 761,
    "ans": ["B"],
    "expl": "Object I's dots start close together and spread out gradually (smaller initial speed, smaller acceleration than II would suggest) — but II's evenly spaced dots show constant velocity while I's increasingly-spaced dots show it speeding up faster over the same interval, so I has the smaller initial speed but the larger average acceleration."
  },
  {
    "id": "JR20-Q3",
    "year": 2020,
    "n": 3,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "JR20_mc03.png",
    "w": 1205,
    "h": 946,
    "ans": ["D"],
    "expl": "Reflection off a straight barrier obeys the law of reflection (angle of incidence = angle of reflection), reflecting the ray back on the same side of the normal it approached from — matching option D's geometry."
  },
  {
    "id": "JR20-Q4",
    "year": 2020,
    "n": 4,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "JR20_mc04.png",
    "w": 1205,
    "h": 853,
    "ans": ["C"],
    "expl": "Train A's position graph is a straight line (constant velocity throughout, so it never 'speeds up'), while Train B's curve starts steeper and flattens (decelerating). Since B starts faster than A but they meet at the same position at t_B with B's curve flattening toward A's slope, the two velocity-time behaviours must cross at some time before t_B."
  },
  {
    "id": "JR20-Q5",
    "year": 2020,
    "n": 5,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "JR20_mc05.png",
    "w": 1205,
    "h": 705,
    "ans": ["A"],
    "expl": "Using Snell's law: n_water sin(70) = n_glass sin(theta). sin(theta) = (1.33 x sin70)/1.52 = (1.33 x 0.940)/1.52 = 0.822, giving theta = 17.4 degrees — light bends towards the normal entering the denser (higher refractive index) glass."
  },
  {
    "id": "JR20-Q6",
    "year": 2020,
    "n": 6,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "JR20_mc06.png",
    "w": 1205,
    "h": 594,
    "ans": ["D"],
    "expl": "Student A is wrong: a resultant force of zero means constant velocity (Newton's First Law), not slowing down. Student B is wrong: a force causes acceleration (a change in motion), not necessarily movement from rest — e.g. a force can act on an already-moving or even balanced object without it starting to move. Neither statement is correct."
  },
  {
    "id": "JR20-Q7",
    "year": 2020,
    "n": 7,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "JR20_mc07.png",
    "w": 1205,
    "h": 538,
    "ans": ["C"],
    "expl": "Applying Newton's Second Law vertically: T - mg = ma, so T = m(g+a) = 10 x (9.8+5) = 148 N, approximately 150 N."
  },
  {
    "id": "JR20-Q8",
    "year": 2020,
    "n": 8,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "JR20_mc08.png",
    "w": 1205,
    "h": 705,
    "ans": ["C"],
    "expl": "With equal force F pulling each mass through the same distance d, the work done (Fd) and hence kinetic energy gained is equal for both — ruling out B. Since the smaller mass reaches a higher final velocity for the same KE, and reaches it in less time, it also has a higher momentum (ruling out A) and impulse (ruling out D). But power = work/time, and since the smaller mass covers the same distance in less time, it receives the same energy over a shorter time — the power delivered to it is higher."
  },
  {
    "id": "JR20-Q9",
    "year": 2020,
    "n": 9,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "JR20_mc09.png",
    "w": 1205,
    "h": 1039,
    "ans": ["A"],
    "expl": "As the ambulance (source) moves towards observer A, the sound waves are compressed ahead of it, so A hears a frequency greater than f. Moving away from observer B, the waves are stretched out behind it, so B hears a frequency less than f."
  },
  {
    "id": "JR20-Q10",
    "year": 2020,
    "n": 10,
    "topic": "Kinematics",
    "subs": ["Motion on a Plane"],
    "img": "JR20_mc10.png",
    "w": 1205,
    "h": 946,
    "ans": ["A"],
    "expl": "Relative velocity of B with respect to A = velocity of B minus velocity of A. With A heading north and B heading east, both at 20 m/s, this vector subtraction (B - A = B + (-A), where -A points south) gives a resultant of magnitude 20*sqrt(2) is approximately 28 m/s, pointing south-east."
  },
  {
    "id": "JR20-Q11",
    "year": 2020,
    "n": 11,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "JR20_mc11.png",
    "w": 1205,
    "h": 890,
    "ans": ["C"],
    "expl": "At the point of sliding, the frictional force F equals its maximum value, and resolving forces along and perpendicular to the incline gives F = W sin(theta) and R = W cos(theta). The coefficient of friction mu = F/R = tan(theta)."
  },
  {
    "id": "JR20-Q12",
    "year": 2020,
    "n": 12,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "JR20_mc12.png",
    "w": 1205,
    "h": 890,
    "ans": ["B"],
    "expl": "The diagram shows the second harmonic of an open pipe (two loops), so 1.2 m = 1 wavelength at 280 Hz, giving a wave speed of 280 x 1.2 = 336 m/s. The fundamental (first harmonic) of an open pipe has a wavelength of 2L = 2.4 m, giving a fundamental frequency of 336/2.4 = 140 Hz."
  },
  {
    "id": "JR20-Q13",
    "year": 2020,
    "n": 13,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "JR20_mc13.png",
    "w": 1205,
    "h": 946,
    "ans": ["C"],
    "expl": "R1 and R2 sit in a single loop with the battery, so they are in series and carry the same current: current through R1 / current through R2 = 1. Using P = I^2 R with that equal current, the power ratio equals the resistance ratio: resistance of R1 / resistance of R2 = P1/P2 = 2/4 = 0.5."
  },
  {
    "id": "JR20-Q14",
    "year": 2020,
    "n": 14,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "JR20_mc14.png",
    "w": 1205,
    "h": 705,
    "ans": ["D"],
    "expl": "By Newton's Third Law, the force (and hence, with equal masses, the acceleration) on X and Y are always equal in magnitude regardless of their different charges. As the oppositely-charged particles accelerate towards each other, the distance between them shrinks, so by Coulomb's Law the force — and acceleration — increases."
  },
  {
    "id": "JR20-Q15",
    "year": 2020,
    "n": 15,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "JR20_mc15.png",
    "w": 1205,
    "h": 1094,
    "ans": ["B"],
    "expl": "With no current, the compass needle points north due to Earth's magnetic field alone. Only the solenoid in option B is oriented so that turning on its current would produce a field along the compass's existing north-south axis (rather than perpendicular to or trivially aligned with it already), so only in B can the needle's orientation be attributed solely to the solenoid's own field."
  },
  {
    "id": "JR20-Q16",
    "year": 2020,
    "n": 16,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "JR20_mc16.png",
    "w": 1205,
    "h": 705,
    "ans": ["A"],
    "expl": "Applying the right-hand grip rule to each of the four conductors and superposing their fields at the centre of the square, the contributions add up to a net magnetic field pointing in direction A."
  },
  {
    "id": "P22-Q1",
    "year": 2022,
    "n": 1,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "P22_mc01.png",
    "w": 1646,
    "h": 785,
    "ans": ["C"],
    "expl": "Acceleration = 2s/t^2 = 2(400)/8^2 = 12.5 m/s^2. Bearing notation requires three digits, so the correctly expressed answer is 12.5 m/s^2 bearing 090 (not '90')."
  },
  {
    "id": "P22-Q2",
    "year": 2022,
    "n": 2,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "P22_mc02.png",
    "w": 1646,
    "h": 1544,
    "ans": ["D"],
    "expl": "The displacement at t = 12 s is the total area under the velocity-time graph up to that time, which (counting the grid squares beneath the curve) works out to about 252 m south."
  },
  {
    "id": "P22-Q4",
    "year": 2022,
    "n": 4,
    "topic": "Kinematics",
    "subs": ["Motion on a Plane"],
    "img": "P22_mc04.png",
    "w": 1644,
    "h": 1012,
    "ans": ["B"],
    "expl": "Measuring Force A against the same scale as the 35 N Force B and combining the two perpendicular vectors with Pythagoras' theorem gives a resultant of about 53 N."
  },
  {
    "id": "P22-Q5",
    "year": 2022,
    "n": 5,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "P22_mc05.png",
    "w": 1644,
    "h": 835,
    "ans": ["D"],
    "expl": "For uniform acceleration, F = ma is constant throughout the motion (since m and a don't change), so the force-time graph is a flat horizontal line."
  },
  {
    "id": "P22-Q6",
    "year": 2022,
    "n": 6,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "P22_mc06.png",
    "w": 1644,
    "h": 759,
    "ans": ["D"],
    "expl": "Power = energy / time. Student X: P = W/t. Student Y: P = 2W/(t/2) = 4W/t. Ratio of X's power to Y's power = (W/t) : (4W/t) = 1:4."
  },
  {
    "id": "P22-Q7",
    "year": 2022,
    "n": 7,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "P22_mc07.png",
    "w": 1644,
    "h": 785,
    "ans": ["A"],
    "expl": "By definition, an elastic collision is one in which both momentum and kinetic energy are conserved."
  },
  {
    "id": "P22-Q8",
    "year": 2022,
    "n": 8,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Properties"],
    "img": "P22_mc08.png",
    "w": 1644,
    "h": 885,
    "ans": ["B"],
    "expl": "The wave's period is T = 1/f = 1/5 = 0.2 s. After exactly one period, a progressive wave repeats its pattern, so the particles return to the same positions shown in the diagram."
  },
  {
    "id": "P22-Q9",
    "year": 2022,
    "n": 9,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "P22_mc09.png",
    "w": 1644,
    "h": 1188,
    "ans": ["C"],
    "expl": "Since the apparent image of an object in a plane mirror sits as far behind the mirror as the object is in front of it, the image of the chair appears 2.0 m behind the mirror. The apparent distance from the person to the image is therefore 4.5 + 2.0 = 6.5 m."
  },
  {
    "id": "P22-Q10",
    "year": 2022,
    "n": 10,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Properties"],
    "img": "P22_mc10.png",
    "w": 1644,
    "h": 481,
    "ans": ["C"],
    "expl": "Wave number describes how many complete wave cycles fit into one metre of the wave's length — it is determined by the number of wave cycles per metre."
  },
  {
    "id": "P22-Q11",
    "year": 2022,
    "n": 11,
    "topic": "Waves and Thermodynamics",
    "subs": ["Thermodynamics"],
    "img": "P22_mc11_q.png",
    "w": 1644,
    "h": 1416,
    "ans": ["B"],
    "expl": "Latent heat of fusion is absorbed while a solid melts into a liquid at a constant temperature. On the heating graph this corresponds to the first flat (plateau) section, QR, before the temperature rises further towards boiling."
  },
  {
    "id": "P22-Q12",
    "year": 2022,
    "n": 12,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "P22_mc12_q.png",
    "w": 1644,
    "h": 1467,
    "ans": ["C"],
    "expl": "Coulomb's Law gives force inversely proportional to the square of the distance. From the diagram, charge Z sits at about half the distance of X from the central charge, so the force on Z is about 1/(0.5)^2 = 4 times as large: approximately 4F."
  },
  {
    "id": "P22-Q13",
    "year": 2022,
    "n": 13,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "P22_mc13.png",
    "w": 1644,
    "h": 1568,
    "ans": ["A"],
    "expl": "X and Y are in series, so the same current flows through both. From the graph, X (an ohmic conductor) carries 8 A at 16 V. That same 8 A flowing through Y corresponds to about 4 V on Y's curve."
  },
  {
    "id": "P22-Q14",
    "year": 2022,
    "n": 14,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "P22_mc14.png",
    "w": 1644,
    "h": 886,
    "ans": ["D"],
    "expl": "Current, I = P/V = 800/240 = 3.3 A."
  },
  {
    "id": "P22-Q15",
    "year": 2022,
    "n": 15,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "P22_mc15.png",
    "w": 1644,
    "h": 784,
    "ans": ["B"],
    "expl": "Applying the right-hand grip rule to the current direction shown, the induced magnetic field is strongest closest to the wire and points out of the page at position Q."
  },
  {
    "id": "IND21-Q1",
    "year": 2021,
    "n": 1,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "IND21_mc01.png",
    "w": 1644,
    "h": 708,
    "ans": ["B"],
    "expl": "Average velocity is total displacement over total time elapsed (including the rest): 500 m / 100 s = 5.0 m/s. East corresponds to a compass bearing of 090°, matching B."
  },
  {
    "id": "IND21-Q2",
    "year": 2021,
    "n": 2,
    "topic": "Kinematics",
    "subs": ["Motion in a Straight Line"],
    "img": "IND21_mc02.png",
    "w": 1644,
    "h": 1567,
    "ans": ["B"],
    "expl": "The object's velocity is constant (a straight line) from t = 0 to t = 4 s, then it is at rest (zero velocity) from t = 4 to t = 8 s. For the object to change from moving to at rest, a force had to act at t = 4.0 s — the first point the graph's slope changes."
  },
  {
    "id": "IND21-Q4",
    "year": 2021,
    "n": 4,
    "topic": "Dynamics",
    "subs": ["Forces"],
    "img": "IND21_mc04.png",
    "w": 1644,
    "h": 1567,
    "ans": ["D"],
    "expl": "From the diagram the chain makes a steep angle with the horizontal. Resolving the 1000 N force: horizontal component = 1000 cosθ ≈ 375 N, vertical component = 1000 sinθ ≈ 927 N (consistent with θ ≈ 68°), matching D."
  },
  {
    "id": "IND21-Q5",
    "year": 2021,
    "n": 5,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_mc05.png",
    "w": 1644,
    "h": 2375,
    "ans": ["C"],
    "expl": "The graph is a straight line through the origin, so the spring's compression (displacement) is directly proportional to the force applied by the truck — this is Hooke's Law behaviour."
  },
  {
    "id": "IND21-Q6",
    "year": 2021,
    "n": 6,
    "topic": "Dynamics",
    "subs": ["Forces, Acceleration and Energy"],
    "img": "IND21_mc06.png",
    "w": 1644,
    "h": 2375,
    "ans": ["A"],
    "expl": "Work done = area under the force-displacement graph = 1/2 × base × height = 1/2 × 0.20 m × 30 N = 3 J (converting 20 cm to 0.20 m before calculating)."
  },
  {
    "id": "IND21-Q7",
    "year": 2021,
    "n": 7,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_mc07.png",
    "w": 1644,
    "h": 935,
    "ans": ["D"],
    "expl": "By conservation of momentum, the impulse on trolley X is equal in magnitude to the impulse on trolley Y, ruling out A and B. Since kinetic energy gained = (impulse)^2 / (2 × mass) for equal impulses, the trolley with the LARGER mass gains LESS kinetic energy — so trolley X (the more massive one) gains less kinetic energy than trolley Y."
  },
  {
    "id": "IND21-Q8",
    "year": 2021,
    "n": 8,
    "topic": "Dynamics",
    "subs": ["Momentum, Energy and Simple Systems"],
    "img": "IND21_mc08.png",
    "w": 1644,
    "h": 632,
    "ans": ["C"],
    "expl": "A seatbelt (together with the car's crumple zones) extends the time over which the wearer's momentum changes during a collision. Since impulse (force × time) is fixed by the change in momentum, a longer collision time means a smaller average force on the person."
  },
  {
    "id": "IND21-Q9",
    "year": 2021,
    "n": 9,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Properties"],
    "img": "IND21_mc09.png",
    "w": 1644,
    "h": 910,
    "ans": ["A"],
    "expl": "In a longitudinal wave, particles oscillate parallel to the direction the wave (and its energy) travels — unlike a transverse wave, where the oscillation is perpendicular to the energy transfer direction."
  },
  {
    "id": "IND21-Q10",
    "year": 2021,
    "n": 10,
    "topic": "Waves and Thermodynamics",
    "subs": ["Wave Behaviour"],
    "img": "IND21_mc10.png",
    "w": 1644,
    "h": 2198,
    "ans": ["D"],
    "expl": "Sound bends around the edges of the gap (diffracts) because the gap's width is comparable to the wavelength of the sound. This is why Jack can hear Jill despite not being able to see her through the gap."
  },
  {
    "id": "IND21-Q11",
    "year": 2021,
    "n": 11,
    "topic": "Waves and Thermodynamics",
    "subs": ["Thermodynamics"],
    "img": "IND21_mc11.png",
    "w": 1644,
    "h": 1238,
    "ans": ["B"],
    "expl": "Heat flows well through the conductor between the hot block X and cool block Y, so both settle to an intermediate 'warm' temperature. The insulator blocks heat reaching Z, which stays cool."
  },
  {
    "id": "IND21-Q12",
    "year": 2021,
    "n": 12,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "IND21_mc12.png",
    "w": 1644,
    "h": 1087,
    "ans": ["C"],
    "expl": "Using Coulomb's Law, F = kq1q2/r². The charge product becomes (2Q)(-0.5Q) = -Q² (opposite signs, so attraction), with the same magnitude as before. Halving the distance increases the force by a factor of 1/(0.5)² = 4, giving 4F attraction."
  },
  {
    "id": "IND21-Q13",
    "year": 2021,
    "n": 13,
    "topic": "Electricity and Magnetism",
    "subs": ["Electrostatics"],
    "img": "IND21_mc13.png",
    "w": 1644,
    "h": 1112,
    "ans": ["A"],
    "expl": "The field lines point upward from the bottom plate to the top plate, so the bottom plate is positive. Between ideal parallel plates the electric field is uniform, so identical charges X and Y experience equal forces regardless of their exact position."
  },
  {
    "id": "IND21-Q14",
    "year": 2021,
    "n": 14,
    "topic": "Electricity and Magnetism",
    "subs": ["Electric Circuits"],
    "img": "IND21_mc14.png",
    "w": 1644,
    "h": 1213,
    "ans": ["A"],
    "expl": "The 4Ω and 2Ω resistors in series form a 6Ω branch, in parallel with the 3Ω branch: total resistance = (6×3)/(6+3) = 2Ω, so total current = 18/2 = 9 A. By the current divider rule, the 6Ω branch (containing the 2Ω resistor) carries 9 × 3/(3+6) = 3 A."
  },
  {
    "id": "IND21-Q15",
    "year": 2021,
    "n": 15,
    "topic": "Electricity and Magnetism",
    "subs": ["Magnetism"],
    "img": "IND21_mc15.png",
    "w": 1644,
    "h": 1567,
    "ans": ["D"],
    "expl": "Applying the right-hand grip rule to each conductor and superposing the four resulting fields at the centre P gives a net magnetic field pointing down the page."
  }
];
